### ISSUE TITLE
Tracking issue for v0.1

### ISSUE THREAD

**Issue by Ottatop** [pinnacle-comp/pinnacle#142]
# v0.1: Arriving at the base of the mountain

This is a tracking issue for the release of v0.1.

These goals are not in order; they are numbered for referencing.

This list will change as I add and remove goals.

- [x] 1. Scaffold an event/signal system (#164)
- [x] 2. Introduce a dynamic layout system (#176)
- [x] 3. Add window gaps (#176)
    - This is contingent on 2.
- [x] 4. API enhancements
    - ~~4a. Pointer and keyboard control (#144)~~ Pushing off to sometime later
    - ~~4b. Ability to apply shaders to windows~~
- ~~5. Highlight border of focused window/focus ring/whatever you want to call it~~
    - ~~This is contingent on 4b.~~
- ~~6. Rounded corners~~
    - ~~This is contingent on 4b.~~
- [x] 7. Fix the dang flickering (#118)
- [x] 8. Session support (#141)
- [x] 9. Add unit tests for things (#127)
- [x] 10. Add sloppy focus (#166)
    - This is contingent on 1.
- [x] 11. Add Nix flake (#200)
    - [ ] 11a. Add package to the flake (#215)
- [x] 12. Implement protocols
    - Implemented in Smithay:
        - [x] Relative pointer
        - [x] Keyboard shortcuts inhibit (4e95a28)
        - [x] Pointer constraints (#225)
        - [x] Pointer gestures (7896d88)
        - [x] Session lock (#238)
        - [x] XDG activation (e50c24c)
        - [x] XDG decoration (036380c)
        - [x] Idle inhibit
        - [x] Idle notify
        - [x] Fractional scale
        - [x] Security context (#227)
    - Must be implemented manually
        - [x] wlr foreign toplevel management (#235)
        - [x] wlr screencopy (#187)
        - [x] wlr gamma control (#197)
        - [x] wlr output management (#244)
        - [x] wlr output power management (#244)
- [x] 13. Add performance profiling (7ddc1a9)
- [x] 14. Scaffold a widget system to show keybindings and an exit menu like Niri (#253 and #256)
- [x] 15. Get HiDPI working (#182)
- [x] 16. Make a wiki website
- [x] 17. Output disabling for idling and stuff (#244)
- [x] 18. Improve libinput settings (#138)

**Comment by Ottatop** [comment]
Eye candy (4b, 5, and 6) is being pushed off into a future, most likely point release in favor of reaching the target feature set to allow for bug fixes, testing, reworking of some aspects of the API, and general stabilization of the compositor.

**Comment by AppleSheeple** [comment]
> Eye candy (**4b**, 5, and 6) is being pushed off into a future

Just found out about this project.
Postponing 4b is unfortunate. Lack of shader support (for custom color inversion) is the number one thing keeping me away from wayland.

**Comment by ildar** [comment]
Greetings!
As I see in the chats, some enthusiasts started to package Pinnacle to
their favorite distros. I personally was waiting for the 0.1 to package too.

It's maybe the right moment to bump the release. Especially as almost ALL
the checkboxes above are checked :-)
