### ISSUE TITLE
Nix Packaging tracking issue

### ISSUE THREAD

**Issue by nixith** [pinnacle-comp/pinnacle#213]
Following the discussions in [Initial packaging questions](https://github.com/pinnacle-comp/pinnacle/discussions/212) I felt it would be best to set up a tracking issue for nix things. Currently on the list:

- 1. Figure out what's going on with [crane](https://github.com/ipetkov/crane) and why their full workspace config works
  - [ ] upstream changes from the [workspace quick start config](https://crane.dev/examples/quick-start-workspace.html)
- 2. work out issues in build system blocking nix
  - [ ] build.rs tries to build outside of `OUT_DIR`, which nix doesn't like
  - [ ] work out how rust config might happen if rustc needs to be available at runtime
  - [ ] figure out the luarocks situation (either roll it as part of 3 or use something like [luarocks-nix](https://github.com/nix-community/luarocks-nix) during build)
- 3. (maybe) nix configuration
  - [ ] direct nix config (probably don't do this)
  - [ ] make lua config from options
  - [ ] however declarative nix -> rust -> compiled config would work

**Comment by nixith** [comment]
Thinking about this,  I think both options have their merits. I think it might be best to have an "unwrapped"  derivation that handles packaging pinnacle and a wrapper that can take in the config values,  which can be exposed similarly to how something like [neovim](https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/applications/editors/neovim/wrapper.nix)  handles it. Home manager or the nixos config can just call the wrapper,  and people desiring static configs and grab the unwrapped package and make a derivation from that.

**Comment by nixith** [comment]
I also would like to throw out a suggestion of maybe using [garnix](https://garnix.io/) to set up a basic project cache, afaik its free (at least they haven't charged me for my usage or asked for a payment method) and [prismlauncher uses it](https://github.com/PrismLauncher/PrismLauncher/tree/develop/nix#installing-a-development-release-flake) so it's probably fine

**Comment by LogicalOverflow** [comment]
Couldn't `pinnacle-config` just be an attrset of the values to be put in the `metaconfig.toml`? Like, the `metaconfig.toml` and config binary don't need to be in the same dir, and with nix we can just use absolute paths to the config binary.

That feels like a nicer interface to me, tho that can rather easily be built on top of your suggestion.

Or maybe making `pinnacle-config`  a derivation that only consists of the `metaconfig.toml` (e.g. as is return from `writeText`) the minimal "pinnacle-wtih-config" helper.

**Comment by nixith** [comment]
Pinnacle-config could be an attrset of that, but that attrset also needs to contain the rust or lua, right? We need to either compile the rust (so we don't need cargo and rustc as a runtime dep) or specify lua packages (to get around luarocks, or at least that's how it's going in my mind)

The point of a separate symlinkJoin was to help facilitate using both. As of now I also have the following:
<details>

  <summary> buildPinnacleRustConfig</summary>

```nix
      buildPinnacleRustConfig = {
        src,
        runCommand ? ["cargo run"],
      }: (
        craneLib.buildPackage (individualCrateArgs
          // {
            pname = "pinnacle-config";
            cargoExtraArgs = "-p pinnacle-config";
            inherit src;
          })
      );
```
</details>

My thoughts were that it should be changed there in the `buildPinnacle<>Config` function, since it means you only have to modify the config derivation to change to another language, i.e. a `buildPinnacleLuaConfig`. Doing it this way also means that people don't need to pull down something like crane or understand how to build a nix derivation, they can just pass their config dir as a `src`. However, if you think it'd be better to do it in the wrapper script, it shouldn't be too difficult of a move.

**Comment by nixith** [comment]
> Couldn't `pinnacle-config` just be an attrset of the values to be put in the `metaconfig.toml`? Like, the `metaconfig.toml` and config binary don't need to be in the same dir, and with nix we can just use absolute paths to the config binary.
> 
> That feels like a nicer interface to me, tho that can rather easily be built on top of your suggestion.
> 
> Or maybe making `pinnacle-config` a derivation that only consists of the `metaconfig.toml` (e.g. as is return from `writeText`) the minimal "pinnacle-wtih-config" helper.

sorry it took me a while to get what you were saying, been a bit of a long day for me. I think a `src` (path) and a `manifest` (attrset of toml - default null) might work well? You could then bundle `src` in as needed, manifest can be written in nix values or, if null, be asserted that it exists in the `src`. If manifest exists we can symlink it in, otherwise it should just get there automatically.

It might also be worth changing names to make it more obvious that a dynamic config is used, i.e. `pinnacle` and `pinnacle-with-config`.

**Comment by nixith** [comment]
Alright, it's not ready for a PR yet but I have a mostly functional rust config builder over at [my fork](https://github.com/nixith/pinnacle/tree/config). Blockers to adding it, both in terms of nix code and rust, are in the README

**Comment by LogicalOverflow** [comment]
I just looked through the fork's flake, and it looks mostly good. Just the `metaconfig.toml` is handled twice (It's copied in `buildPinnacleRustConfigPackage` and generated in `mergePinnacleRustConfig`) and I think that could lead to some conflicts. But if that's clean up a bit, I think what you're version also makes sense.

(What follows is just some clarification on how I thought about the packaging flow, feel free to not use any of it)

> sorry it took me a while to get what you were saying, been a bit of a long day for me.

Same, and I don't think I did a particular good job of explaining my ideas either. After a night of sleep, here a (hopefully) clearer explanation of how I thought it could look like.

The basic structure of "building a pinnacle with config" I have in mind looks like this:

```
various utility functions to
build config derivations from
rust/lua in different settings
             |
             V
+------------------------+
| config derivation      |
| contains:              |      +--------------------+
| - /metaconfig.toml     |      | unwrapped pinnacle |
| - possible more files  |      +--------------------+
|   (e.g. config binary) |                 |
+------------------------+                 |
             |                             |
             +-> mergePinnacleWithConfig <-+
             (just does a 'wrapProgram' to
              add '--config-dir $configDrv'
              as a flag)
```

It's similar to what you have now, just that the config derivation keeps stuff in `/` not `/share/config` in the derivation and
`mergePinnacleWithConfig` does not `symlinkJoin` the two, but just adds a wrapper to pinnacle, adds the `--config-dir` flag.

`buildPinnacleRustConfigPackage` would be one of the functions outputting a config derivation. Another one could be something like `pinnacleConfigFromExecutable { reload_keybind, kill_keybind, config_binary }` which just builds a `metaconfig.toml` with the given options.

If the config requires some run-time setup (like adding a rust toolchain to the path), we can just add a wrapper script around the command starting the config. To make it easier to use, we can provide helper functions for "usual cases" (e.g. run-time compiled rust without any special dependencies).
